name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: magras/byedpi

    - uses: docker/login-action@v3
      with:
        username: magras
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{github.ref_type == 'branch' && github.ref_name == 'main'}}
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
